### PR TITLE
Fix #6, #7, and #8

### LINKED ISSUE #6: Bug in recursive search?
The case I am describing here is covered by unit tests but I think it's a bug both in implementation and tests.

Test JSON:

```
{
    "A":["string",23.3,3,true,false,null],
    "B":"value",
    "C":3.14,
    "D":{
        "C":3.1415,
        "V":["string2",{"C":3.141592}]
    }
}
```

Expression: `$..C` or `$..["C"]`.

Actual results:

```
[3.1415, 3.141592]
```

Expected results:

```
[3.14, 3.1415, 3.141592]
```

Other parsers (https://github.com/PaesslerAG/jsonpath and https://codebeautify.org/jsonpath-tester) work as expected.

### PR DESCRIPTION
**Pull request by gavv**
See #6, #7, #8.

### CODE REVIEW

**Comment by marcc-orange** [comment]
@gavv Oh! I did not expect a PR ! Thanks for your work.

**Comment by marcc-orange** [comment]
I have been working on #6 and just came here to fix and saw your work... well my solution is close to 6401488 but I don't understand why all the fuss with the `type searchResults []interface{}`. Check my PR #10.

**Comment by marcc-orange** [comment]
LGTM 👍

**Comment by gavv** [comment]
> Ok, just understood #7 for squashing inner search results so I suppose the searchResults type is for that and not the recursive search bug.

Right. The commit message is a bit confusing, actually the first commit fixes both #6 and #7.

**Pull request merged**
